{% set name = "wield.declarative" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wield.declarative-{{ version }}.tar.gz
  sha256: f6e81ca0a61c890dd2304677923051b49d577c74e7ee9e73f8a9a78509eda611

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=45
    - wheel
    - pip
  run:
    - python >=3.6
    - numpy

test:
  imports:
    - wield.declarative
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wieldphysics/wield-declarative
  summary: Base classes and methods for declarative object instantiation
  license: Apache-2.0
  license_file: LICENSES/

extra:
  recipe-maintainers:
    - mccullerlp 
